# Generated by Django 2.2.8 on 2020-04-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200420_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojavida',
            name='suscripcion',
            field=models.IntegerField(choices=[(0, 'Finalizada'), (1, 'Activa')], default=0),
        ),
    ]
