# Generated by Django 2.2.8 on 2020-04-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_hojavida_suscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojavida',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='hojavida',
            name='birth_date',
            field=models.DateField(verbose_name='Fecha de nacimiento(mm/dd/yyyy)'),
        ),
        migrations.AlterField(
            model_name='hojavida',
            name='formacion',
            field=models.TextField(verbose_name='Formación académica'),
        ),
    ]
