# Generated by Django 2.2.8 on 2020-04-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_stars_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='Escribe el porqué dejas este comentario y calificación'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='stars_count',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=2, verbose_name='calificación'),
        ),
    ]
